/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3a0e506c-0393-4b1f-a77f-cb35d64dec91",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Y2feD4BQD",
    "aws_user_pools_web_client_id": "17fbbjhm4om2p1ckhocgcpq7is",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://oxx5yrkrjfd63bdcv5p2ndh7qi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qrw4uub4x5fczesphmvle7xuxi"
};


export default awsmobile;
